<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pn_uniform_product_names"
 *
 * Auto generated by Extension Builder 2020-01-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Uniform product names',
    'description' => 'Import and select in page properties the uniform names of products and services of The Dutch government.',
    'category' => 'be',
    'author' => 'Jacco van der Post',
    'author_email' => 'jacco.vanderpost@proudnerds.com',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => 'typo3temp/pn_uniform_product_names',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.6',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
